### ISSUE TITLE
Resize handle out of reach when window larger than screen

### ISSUE THREAD

**Issue by trumank** [SamsDRGMods/DRGLibDevkitFiles#3]
If a window is opened and has a with or height larger than the size of the screen, the resize handle in the lower right cannot be reached so cannot be used to shrink the window. A possible solution may be to add resize handles to all sides of the window.

It can be worked around by maximizing the window and making the handle visible, so not a critical issue.

**Comment by samamstar** [comment]
Ugh I knew you'd ask for this. Curse you and your demands for improvements that I should have added ages ago! I'll look into it. Unfortunately, implementing proper window resizing options will almost certainly be non-trivial, and possibly impossible. Either way this won't be coming anytime soon

Wait you're saying it's possible to create windows larger than the screen? That's the real bug here

**Comment by samamstar** [comment]
Oh of course, if you play in windowed mode it would let you drag the mouse off screen...

**Comment by trumank** [comment]
Oh this is the devkit repo... Oops

**Comment by samamstar** [comment]
lol
